apiVersion: v1
kind: Pod
metadata:
  name: my-db
spec:
  containers:
  - name: my-db
    image: 673896343304.dkr.ecr.us-east-1.amazonaws.com/assignment-mamad:db
    env:
    - name: MYSQL_ROOT_PASSWORD
      valueFrom:
        secretKeyRef:
          name: secret-db
          key: pass
    ports:
    - containerPort: 3306
  dnsPolicy: ClusterFirst
  restartPolicy: Always