apiVersion: v1
kind: Pod
metadata:
  name: my-webapp
spec:
  containers:
  - name: my-webapp
    image: 673896343304.dkr.ecr.us-east-1.amazonaws.com/assignment-mamad:app-v1
    env:
    - name: DBHOST
      value: 10.244.0.6
    - name: DBPWD
      valueFrom:
        secretKeyRef:
          name: secret-db
          key: pass
    - name: DBPORT
      value: '3306'
    - name: DBUSER
      value: root
    ports:
    - containerPort: 8080
  dnsPolicy: ClusterFirst
  restartPolicy: Always
