apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-webapp
  labels:
    app: employees
    version: v1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: employees
      version: v1
  template:
    metadata:
      labels:
        app: employees
        version: v1
    spec:
      containers:
      - name: my-webapp
        image: 673896343304.dkr.ecr.us-east-1.amazonaws.com/assignment-mamad:app-v1
        env:
        - name: DBHOST
          value: 10.244.0.6
        - name: DBPWD
          valueFrom:
            secretKeyRef:
              name: secret-db
              key: pass
        - name: DBPORT
          value: '3306'
        - name: DBUSER
          value: root
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 8080
